/** Textes UI du site — français */
export const copy = {
  nav: {
    work: "Travaux",
    showreel: "Showreel",
    about: "À propos",
    clients: "Clients",
    contact: "Contact",
    letsTalk: "Discutons",
    menu: "Menu",
    search: "Recherche",
  },
  hero: {
    carouselLabel: "Présentation principale",
    viewWork: "Voir les travaux",
    slidePrev: "Slide précédente",
    slideNext: "Slide suivante",
    goToSlide: (n: number) => `Aller à la slide ${n}`,
  },
  about: {
    label: "À propos",
    title: "Créer des histoires visuelles",
    stats: {
      projects: "Projets",
      clients: "Clients",
      years: "Années",
    },
  },
  showreel: {
    label: "Showreel",
    title: "Le mouvement en action",
    subtitle:
      "Une sélection de mes meilleures animations et réalisations motion design.",
    play: "Lire le showreel",
    close: "Fermer",
  },
  portfolio: {
    label: "Portfolio",
    title: "Réalisations",
    subtitle:
      "Une sélection de projets branding, motion, réseaux sociaux et plus.",
    all: "Tout",
    empty: "Aucun projet dans cette catégorie.",
  },
  clients: {
    label: "Clients",
    title: "Ils nous ont fait confiance",
    marqueeLabel: "Logos de clients",
    emptyLogos: "Ajoutez vos logos dans public/clients/ et mettez à jour CLIENT_LOGOS.",
  },
  contact: {
    label: "Contact",
    title: "Créons ensemble",
    subtitle: "Un projet en tête ? Discutons-en.",
    whatsappDirect: "Message direct",
    email: "E-mail",
    placeholders: {
      name: "Nom",
      email: "E-mail",
      message: "Message",
    },
    sending: "Envoi en cours…",
    send: "Envoyer le message",
    success: "Message envoyé avec succès !",
    error: "Erreur — réessayez plus tard.",
  },
  footer: {
    tagline:
      "Designer graphique & motion designer — création d'expériences visuelles cinématiques dans le monde entier.",
    rights: (year: number, name: string) =>
      `© ${year} ${name}. Tous droits réservés.`,
    credit: "Conçu avec mouvement et précision",
  },
  project: {
    notFound: "Projet introuvable",
    overview: "Aperçu",
    problem: "Problème",
    solution: "Solution",
    process: "Processus créatif",
    colorPalette: "Palette de couleurs",
    typography: "Typographie",
    motionPreview: "Aperçu motion",
    beforeAfter: "Avant / Après",
    before: "Avant",
    after: "Après",
    gallery: "Galerie",
    backToWork: "Retour aux travaux",
    startProject: "Démarrer un projet",
  },
  admin: {
    title: "Administration CMS",
    portfolio: "Portfolio Chacross Mafuala",
    login: "Connexion",
    email: "E-mail",
    password: "Mot de passe",
    signIn: "Se connecter",
    configureSupabase:
      "Configurez NEXT_PUBLIC_SUPABASE_URL et ANON_KEY dans .env.local",
    cmsTitle: "CMS — Chacross Mafuala",
    viewSite: "Voir le site",
    logout: "Déconnexion",
    projects: "Projets",
    testimonials: "Témoignages",
    new: "Nouveau",
    edit: "Modifier",
    delete: "Supprimer",
    deleteProject: "Supprimer ce projet ?",
    deleteConfirm: "Supprimer ?",
    saving: "Enregistrement…",
    saved: "Enregistré !",
    deleted: "Supprimé",
    newProject: "Nouveau projet",
    editProject: "Modifier le projet",
    save: "Enregistrer",
    cancel: "Annuler",
    fields: {
      title: "Titre",
      slug: "Slug",
      excerpt: "Extrait",
      coverImage: "URL image de couverture",
      heroImage: "URL image hero",
      videoUrl: "URL vidéo",
      overview: "Aperçu",
      category: "Catégorie",
    },
    setupHint:
      "Configurez Supabase dans .env.local, puis connectez-vous sur",
  },
} as const;
